In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
#Carico in un dataframe il file game.csv contente i dati su tutte le partite dal 1946 al 2023
path = os.path.join('Data','Raw')
nome_file = 'game.csv'

df = pd.read_csv( os.path.join( path, nome_file ) )

df.insert(0, 'year', df['game_date'].str[:4].astype(int))

#Visualizzo i nomi delle colonne per facilitare i passi successivi
df.columns

Index(['year', 'season_id', 'team_id_home', 'team_abbreviation_home',
       'team_name_home', 'game_id', 'game_date', 'matchup_home', 'wl_home',
       'min', 'fgm_home', 'fga_home', 'fg_pct_home', 'fg3m_home', 'fg3a_home',
       'fg3_pct_home', 'ftm_home', 'fta_home', 'ft_pct_home', 'oreb_home',
       'dreb_home', 'reb_home', 'ast_home', 'stl_home', 'blk_home', 'tov_home',
       'pf_home', 'pts_home', 'plus_minus_home', 'video_available_home',
       'team_id_away', 'team_abbreviation_away', 'team_name_away',
       'matchup_away', 'wl_away', 'fgm_away', 'fga_away', 'fg_pct_away',
       'fg3m_away', 'fg3a_away', 'fg3_pct_away', 'ftm_away', 'fta_away',
       'ft_pct_away', 'oreb_away', 'dreb_away', 'reb_away', 'ast_away',
       'stl_away', 'blk_away', 'tov_away', 'pf_away', 'pts_away',
       'plus_minus_away', 'video_available_away', 'season_type'],
      dtype='object')

In [3]:
#Esploro il dataframe
df[(df['year']==1998) & (df['fg3a_home']==0)]

,year,season_id,team_id_home,team_abbreviation_home,team_name_home,game_id,game_date,matchup_home,wl_home,min,...,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,plus_minus_away,video_available_away,season_type
33642,1998,21997,1610612755,PHI,Philadelphia 76ers,29700844,1998-03-04 00:00:00,PHI vs. MIL,W,240,...,46.0,15.0,8.0,8.0,21.0,27.0,80.0,-7,0,Regular Season

In [4]:
#Dalle ultime righe si nota la presenza di dati duplicati, elimino dunque i duplicati basando la ricerca sulla colonna 'game_id'
df.drop_duplicates('game_id', inplace=True)
df

,year,season_id,team_id_home,team_abbreviation_home,team_name_home,game_id,game_date,matchup_home,wl_home,min,...,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,plus_minus_away,video_available_away,season_type
0,1946,21946,1610610035,HUS,Toronto Huskies,24600001,1946-11-01 00:00:00,HUS vs. NYK,L,0,...,NaN,NaN,NaN,NaN,NaN,NaN,68.0,2,0,Regular Season
1,1946,21946,1610610034,BOM,St. Louis Bombers,24600003,1946-11-02 00:00:00,BOM vs. PIT,W,0,...,NaN,NaN,NaN,NaN,NaN,25.0,51.0,-5,0,Regular Season
2,1946,21946,1610610032,PRO,Providence Steamrollers,24600002,1946-11-02 00:00:00,PRO vs. BOS,W,0,...,NaN,NaN,NaN,NaN,NaN,NaN,53.0,-6,0,Regular Season
3,1946,21946,1610610025,CHS,Chicago Stags,24600004,1946-11-02 00:00:00,CHS vs. NYK,W,0,...,NaN,NaN,NaN,NaN,NaN,22.0,47.0,-16,0,Regular Season
4,1946,21946,1610610028,DEF,Detroit Falcons,24600005,1946-11-02 00:00:00,DEF vs. WAS,L,0,...,NaN,NaN,NaN,NaN,NaN,NaN,50.0,17,0,Regular Season
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65692,2023,42022,1610612743,DEN,Denver Nuggets,42200402,2023-06-04 00:00:00,DEN vs. MIA,L,240,...,31.0,28.0,5.0,4.0,11.0,22.0,111.0,3,1,Playoffs
65693,2023,42022,1610612748,MIA,Miami Heat,42200403,2023-06-07 00:00:00,MIA vs. DEN,L,240,...,58.0,28.0,3.0,5.0,14.0,18.0,109.0,15,1,Playoffs
65694,2023,42022,1610612748,MIA,Miami Heat,42200404,2023-06-09 00:00:00,MIA vs. DEN,L,240,...,34.0,26.0,11.0,7.0,8.0,18.0,108.0,13,1,Playoffs
65695,2023,42022,1610612743,DEN,Denver Nuggets,42200405,2023-06-12 00:00:00,DEN vs. MIA,W,240,...,44.0,18.0,9.0,7.0,8.0,21.0,89.0,-5,1,Playoffs
65696,2023,32022,1610616834,LBN,Team LeBron,32200001,2023-02-19 00:00:00,LBN vs. GNS,L,221,...,46.0,43.0,8.0,1.0,12.0,2.0,184.0,9,1,All-Star

In [5]:
#Controllo quali sono tutti i possibili valori della colonna 'season_type', che indica a quale tipo di partita di riferisce la relativa osservazione
tipo_match = df['season_type'].drop_duplicates()
tipo_match

0        Regular Season
331            Playoffs
1918           All-Star
8937           All Star
43591        Pre Season
Name: season_type, dtype: object

In [6]:
#Inserisco una colonna con l'anno in cui si sono disputate le partite

In [7]:
#Il tiro da 3 è stato aggiunto al regolamento dal 1979, escludo quindi i dati relativi alle stagioni precedenti.
#Escludo inoltre i dati relativi a tutti i match non validi per il campionato, quindi le amichevoli Pre-season e le esibizioni degli All Star
df = df[(df['year']>=1979) & ((df['season_type']=='Regular Season') | (df['season_type']=='Playoffs'))]

#Considero solo le colonne utili alle considerazioni sull'analisi dei tiri da 3 per annata
df = df.loc[:,['year','fg3m_home','fg3a_home','fg3m_away','fg3a_away']]
df

       year  fg3m_home  fg3a_home  fg3m_away  fg3a_away
12660  1979        NaN        NaN        NaN        NaN
12661  1979        NaN        NaN        NaN        NaN
12662  1979        NaN        NaN        NaN        NaN
12663  1979        NaN        NaN        NaN        NaN
12664  1979        NaN        NaN        NaN        NaN
...     ...        ...        ...        ...        ...
65691  2023        8.0       27.0       13.0       39.0
65692  2023       11.0       28.0       17.0       35.0
65693  2023       11.0       35.0        5.0       18.0
65694  2023        8.0       25.0       14.0       28.0
65695  2023        5.0       28.0        9.0       35.0

[51424 rows x 5 columns]

In [8]:
#Le prime righe presentano valori NaN, verifico per quante annate si verifica questa evenienza
df.groupby('year').count()

      fg3m_home  fg3a_home  fg3m_away  fg3a_away
year
1979        427          0        427          0
1980        974          6        974          6
1981        878         28        878         28
1982       1004        142       1004        142
1983        989        102        989        102
1984       1032         96       1032         96
1985       1015        481       1015        481
1986        979        979        979        979
1987        981        981        981        981
1988       1064       1064       1064       1064
1989       1121       1121       1121       1121
1990       1185       1185       1185       1185
1991       1184       1184       1184       1184
1992       1147       1147       1147       1147
1993       1193       1193       1193       1193
1994       1109       1109       1109       1109
1995       1222       1222       1222       1222
1996       1201       1201       1201       1201
1997       1262       1262       1262       1262
1998        837        837        837        837
1999       1213       1213       1213       1213
2000       1206       1206       1206       1206
2001       1253       1253       1253       1253
2002       1205       1205       1205       1205
2003       1279       1279       1279       1279
2004       1247       1247       1247       1247
2005       1322       1322       1322       1322
2006       1252       1252       1252       1252
2007       1309       1309       1309       1309
2008       1332       1332       1332       1332
2009       1316       1316       1316       1316
2010       1321       1321       1321       1321
2011        885        885        885        885
2012       1018       1018       1018       1018
2013        551        551        551        551
2014       1334       1334       1334       1334
2015       1319       1319       1319       1319
2016       1333       1333       1333       1333
2017       1347       1347       1347       1347
2018       1316       1316       1316       1316
2019       1267       1267       1267       1267
2020        706        706        706        706
2021       1625       1625       1625       1625
2022       1336       1336       1336       1336
2023        768        768        768        768

In [9]:
#Osservando il conteggio dei valori si nota che fino al 1985 incluso vi sono dei problemi nella rilevazione di alcuni dati,
#in particolare per quanto concerne il numero di tiri da 3 tentati dalle squadre. Considero solo le stagionii in cui ho le osservazioni complete
df = df[(df['year']>=1986)]

#Verifico di non trovare altri valori nulli
df.isnull().sum()

year         0
fg3m_home    0
fg3a_home    0
fg3m_away    0
fg3a_away    0
dtype: int64

In [10]:
#A questo punto reimposto il contatore delle righe del dataframe e 
df.reset_index(inplace=True)
df = df.loc[:,'year':]

#Rinomino le colonne con nomi più intellegibili
df.rename(columns={'fg3m_home' : 'made_home', 'fg3a_home' : 'attempted_home',	'fg3m_away' : 'made_away', 'fg3a_away' : 'attempted_away'}, inplace=True)

#Salvo i dati ricavati in formato Parquet per successive analisi
df.to_parquet( os.path.join('Data','Parquet','threePointsTotal.parquet') )